/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClearBtn: typeof import('./src/components/Buttons/ClearBtn.vue')['default']
    LoadBtn: typeof import('./src/components/Buttons/LoadBtn.vue')['default']
    ModalView: typeof import('./src/components/Modals/ModalView.vue')['default']
    SaveBtn: typeof import('./src/components/Buttons/SaveBtn.vue')['default']
    ScoreEditor: typeof import('./src/components/ScoreEditor.vue')['default']
    ScoreHead: typeof import('./src/components/Scores/ScoreHead.vue')['default']
    ScoreMainStats: typeof import('./src/components/Scores/ScoreMainStats.vue')['default']
    ScoresAdd: typeof import('./src/components/Scores/ScoresAdd.vue')['default']
    ScoreSelector: typeof import('./src/components/Scores/ScoreSelector.vue')['default']
    ScoreTable: typeof import('./src/components/Scores/ScoreTable.vue')['default']
    ScoreView: typeof import('./src/components/Scores/ScoreView.vue')['default']
    UploadArea: typeof import('./src/components/UploadArea.vue')['default']
  }
}
