/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ClearBtn: (typeof import("./../components/Buttons/ClearBtn.vue"))["default"];
    GambaChara: (typeof import("./../components/GambaChara.vue"))["default"];
    GambaCharacters: (typeof import("./../components/GambaCharacters.vue"))["default"];
    GambaSlot: (typeof import("./../components/GambaSlot.vue"))["default"];
    GambaSlots: (typeof import("./../components/GambaSlots.vue"))["default"];
    IMdiBellOutline: (typeof import("~icons/mdi/bell-outline"))["default"];
    IMdiMail: (typeof import("~icons/mdi/mail"))["default"];
    LoadBtn: (typeof import("./../components/Buttons/LoadBtn.vue"))["default"];
    MessageContent: (typeof import("./../components/Messages/MessageContent.vue"))["default"];
    MessageContentImage: (typeof import("./../components/Messages/MessageContentImage.vue"))["default"];
    MessageOptions: (typeof import("./../components/Messages/MessageOptions.vue"))["default"];
    MessagesConfig: (typeof import("./../components/Messages/MessagesConfig.vue"))["default"];
    MessageSwitcher: (typeof import("./../components/Messages/MessageSwitcher.vue"))["default"];
    MessageView: (typeof import("./../components/Messages/MessageView.vue"))["default"];
    ModalView: (typeof import("./../components/Modals/ModalView.vue"))["default"];
    NavButton: (typeof import("./../components/NavButton.vue"))["default"];
    QingqueIcon: (typeof import("./../components/QingqueIcon.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    SaveBtn: (typeof import("./../components/Buttons/SaveBtn.vue"))["default"];
    ScoreEditor: (typeof import("./../components/ScoreEditor.vue"))["default"];
    ScoreHead: (typeof import("./../components/Scores/ScoreHead.vue"))["default"];
    ScoreMainStats: (typeof import("./../components/Scores/ScoreMainStats.vue"))["default"];
    ScoresAdd: (typeof import("./../components/Scores/ScoresAdd.vue"))["default"];
    ScoreSelector: (typeof import("./../components/Scores/ScoreSelector.vue"))["default"];
    ScoreTable: (typeof import("./../components/Scores/ScoreTable.vue"))["default"];
    ScoreView: (typeof import("./../components/Scores/ScoreView.vue"))["default"];
    UploadArea: (typeof import("./../components/UploadArea.vue"))["default"];
  }
}
